### ISSUE TITLE
Move version to variable (no hardcode, plz)

### ISSUE THREAD

**Issue by jtoming830** [ksercs/dx-gitAutomation#1]

**Comment by ksercs** [comment]
Do you mean master version for new branch creating and for cherry-picking?

**Comment by jtoming830** [comment]
yes, coz we will need manually update versions every 6 months. It's OK if versions are in some config file and bad if versions are hardcoded in the script.

**Comment by ksercs** [comment]
Thank you for the feedback, we will fix the issue in the next release (2020, December)
